// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-zBAShz-2S85_YUwfXV9BZloBdKPYs44',
    appId: '1:283976194085:web:f19084708e636ef80a47cc',
    messagingSenderId: '283976194085',
    projectId: 'economizze-b9b91',
    authDomain: 'economizze-b9b91.firebaseapp.com',
    databaseURL: 'https://economizze-b9b91-default-rtdb.firebaseio.com',
    storageBucket: 'economizze-b9b91.appspot.com',
    measurementId: 'G-WSY224PQER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuOPW5b6mIeHUWQFmxu884gq5ytehzUrI',
    appId: '1:283976194085:android:e813051cd61e145d0a47cc',
    messagingSenderId: '283976194085',
    projectId: 'economizze-b9b91',
    databaseURL: 'https://economizze-b9b91-default-rtdb.firebaseio.com',
    storageBucket: 'economizze-b9b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cd0WHN-3rLwdcLMnoRkp8erwFK9gJjE',
    appId: '1:283976194085:ios:5547c63ca31358e00a47cc',
    messagingSenderId: '283976194085',
    projectId: 'economizze-b9b91',
    databaseURL: 'https://economizze-b9b91-default-rtdb.firebaseio.com',
    storageBucket: 'economizze-b9b91.appspot.com',
    iosClientId: '283976194085-tpmtinjkrf7joopfrg7pu8fsv4ub6sg2.apps.googleusercontent.com',
    iosBundleId: 'com.economizze.app',
  );
}
